[project]
name = "logistics-llm-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "black>=26.5.1",
    "chromadb>=1.5.9",
    "isort>=8.0.1",
    "langchain-chroma>=1.1.0",
    "langchain-text-splitters>=1.1.2",
]
